backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://browsbeforebros.ru
logo_url: https://browsbeforebros.ru/static/img/marker@2x.png

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
locale: ru
collections:
  - label: "Блог"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Время публикации", name: "date", widget: "datetime" }
      - { label: "Содержимое", name: "body", widget: "markdown" }
      - widget: select
        label: "Теги"
        name: "tags"
        multiple: true
        create: true
        options: ["Брови", "Ресницы", "Обучение", "Работы"]
  - label: "Настройка"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Навигация"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Ссылки"
            label_singular: "ссылка"
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Подпись", name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Прайс"
        name: "price"
        file: "src/_data/price.yaml"
        fields:
          - label: "Категории услуг"
            label_singular: "категория"
            name: categories
            widget: list
            collapsed: false
            fields:
              - { label: "Название", name: title, widget: string }
              - label: "Услуги"
                label_singular: "услуга"
                name: services
                widget: list
                collapsed: false
                fields:
                  - { label: "Название", name: title, widget: string }
                  - { label: "Описание", name: desc, widget: string, required: false }
                  - { label: "Цена", name: price, widget: string, required: false }
                  - { label: "Продолжительность", name: duration, widget: string, required: false }
